-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 21:52:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crudproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crudproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crudproject` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crudproject` ;

-- -----------------------------------------------------
-- Table `crudproject`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crudproject`.`category` (
  `categoryid` VARCHAR(255) NOT NULL,
  `category_img` VARCHAR(255) NULL DEFAULT NULL,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`categoryid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `crudproject`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crudproject`.`product` (
  `productid` VARCHAR(255) NOT NULL,
  `categoryid` VARCHAR(255) NULL DEFAULT NULL,
  `product_img` VARCHAR(300) NOT NULL,
  `product_name` VARCHAR(300) NOT NULL,
  `product_numbers` INT NOT NULL,
  `product_price` INT NOT NULL,
  PRIMARY KEY (`productid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
